### ISSUE TITLE
Issue with URL list file

### ISSUE THREAD

**Issue by gaspo53** [tonikelope/megadown#13]
Hi!

Is there any tricky syntax for passing a file? Because I can't get this working:

`ERROR: MEGA/MC link or --list parameter is required

gaspar at Macarena in ~/Downloads/megadown on master [?]
$ ./megadown --list sultan_mega_list
`
`ERROR: MEGA/MC link or --list parameter is required

gaspar at Macarena in ~/Downloads/megadown on master [?]
$ ./megadown -l sultan_mega_list` 

Thanks

**Comment by tonikelope** [comment]
Hi. Try to put full path to link list file.

Regards.
