### ISSUE TITLE
Oooops, download failed! EXIT CODE (22)

### ISSUE THREAD

**Issue by Wenzel** [tonikelope/megadown#16]
Hi !

I'm trying to use your script to download a big file from my mega account.

The problem is that it fails instantly, with a an exit code `22`:
![screenshot from 2018-07-04 01-40-40](https://user-images.githubusercontent.com/964610/42247853-5b7e79c2-7f2b-11e8-8840-1a485ce0e713.png)

Any idea what's wrong here ?

I tried with smaller files like 15Mb, and it was working, so I don't see what could be wrong ?

Thank you !

**Comment by Wenzel** [comment]
I found #12 , i guess it's the same issue.

**Comment by tonikelope** [comment]
It's planned implementing some kind of "solution" yo mitigate this. ASAP...

**Comment by lzrobots** [comment]
Hi I am wondering if this is solved in this repo? Thanks.
