### ISSUE TITLE
Megadown simply fails to download

### ISSUE THREAD

**Issue by pitsi** [tonikelope/megadown#18]
As the title says, megadown fails like so
```
$ megadown https://mega.nz/#!3QsG0IDJ!wnEhMRAj1UsXvH3BmWKfr5Z4wqMD2c5ru4iWgFzJmO0'﻿
﻿	Reading link metadata...
	MEGA bad link
```
At first I thought it was my distro's (debian testing/unstable) old package, because it is based on commit 83c53dd, the last one for 2018, or version 1.9.39.
So, I removed it completely, downloaded the bash file from your repo (version 1.9.45) and tried again, but still no luck. The output is the same.

Commenting out the lines from 464 to 466 makes it work, as it downloads a file named ".temp" which I have to rename afterwards, but then the downloaded file possibly gets corrupted as seen from the sums here
```
$ md5sum *.apk
cfdbb312c7a428f409a538e00b919532  QP Gallery 7.5-browser.apk
47ff28a0b3b4d5b78217bb2ed002dc8f  QP Gallery 7.5-megadown.apk
```
The first file was downloaded via the browser and the second one via megadown.

---edit
fixed 2 typos

**Comment by tonikelope** [comment]
There was a bug extracting the key from the file. It's already fixed. Thanks for warning.

**Comment by pitsi** [comment]
Thank you :)

```
$ megadown 'https://mega.nz/#!3QsG0IDJ!wnEhMRAj1UsXvH3BmWKfr5Z4wqMD2c5ru4iWgFzJmO0'

Reading link metadata...

Downloading QP Gallery 7.5.apk [1.0 MB] ...

1.02MiB 0:00:01 [ 617KiB/s] [================================>] 100%            

FILE DOWNLOADED!


$ md5sum QP\ Gallery\ 7.5.apk 
cfdbb312c7a428f409a538e00b919532  QP Gallery 7.5.apk
```
