### ISSUE TITLE
[Help] How do I download a file from a folder hosted in mega.nz?

### ISSUE THREAD

**Issue by pitsi** [tonikelope/megadown#21]
I sometimes come across folders in mega.nz that contain a lot of files. And most of the time I only need one or two of them, so I right click on it and select "get link". Then a small popup comes up with 3 "tabs": 

a) link without key
![2019-11-14-211903_1280x1024_scrot](https://user-images.githubusercontent.com/5880037/68890595-df517d00-0727-11ea-81e5-90d6bb69051e.png)

b) decryption key
![2019-11-14-211907_1280x1024_scrot](https://user-images.githubusercontent.com/5880037/68890608-e9737b80-0727-11ea-88ea-ab9f55677896.png)

c) link with key
![2019-11-14-211913_1280x1024_scrot](https://user-images.githubusercontent.com/5880037/68890629-f3957a00-0727-11ea-8835-a6dd5ab8d7d5.png)

When I try the first one, the link without key, megadown fails
```
$ megadown 'https://mega.nz/#(first part with 11 characters)?(second part with 8 characters)'

Reading link metadata...

Oooops, something went bad. EXIT CODE (3)

```
and the same happens when I try the third one, the link with key
```
$ megadown 'https://mega.nz/#(first part with 11 characters)!(the key with 22 characters)?(second part with 8 characters)'

Reading link metadata...

Oooops, something went bad. EXIT CODE (3)
```

Please note the "#", "!" and "?" special characters that are placed at the beginning of each part, seperating it from the previous one. I would emphasize them, but github's markdown language does not allow bold letters inside code tags.

So, how shall I download such a file?
Megadown 1.9.46.

**Comment by tonikelope** [comment]
Well, with that information I can't know what's going on. Could you pass me the exact link for private?

Regards.

**Comment by pitsi** [comment]
True, but how do i send a p.m. in github? I will email it to you, if you do not mind.

**Comment by pitsi** [comment]
I found a folder with legal content in it in case you want to try
`https://mega.nz/#F!jc8xGKaZ!vGTFXtGV5OsP_EcLISauvQ`

**Comment by tonikelope** [comment]
Folder links are not supported sorry. I recommend to use this ->
https://github.com/tonikelope/megabasterd


Regards

**Comment by pitsi** [comment]
I am mainly using megadown on my server that has no gui, so megabasterd is no use. And I also dislike java apps.
Anyway, since there is no way to download it with megadown, I am closing this issue.
