### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by muhammedfurkan** [tonikelope/megadown#22]
ERROR: there are dependencies not present!

**Comment by ElonSatoshi** [comment]
It should tell you what dependency it's missing. For example this is what I got when I installed it:

```
[pv] is required and it's not installed

ERROR: there are dependencies not present!
```

I fixed it by running:

```
sudo apt install pv
```

**Comment by muhammedfurkan** [comment]
> It should tell you what dependency it's missing. For example this is what I got when I installed it:
> 
> ```
> [pv] is required and it's not installed
> 
> ERROR: there are dependencies not present!
> ```
> 
> I fixed it by running:
> 
> ```
> sudo apt install pv
> ```

how can I install for Heroku ?
