### ISSUE TITLE
New link problem - fix

### ISSUE THREAD

**Issue by amuham3d** [tonikelope/megadown#23]
In case if someone have this error: 

`Reading link metadata...`
`Oooops, something went bad. EXIT CODE (3)`

and you're using new link format, 
E.g 
new `https://mega.nz/file/xxxxxx` 
old `https://mega.nz/#!xxxxxx`

just convert it to old one :
https://github.com/tonikelope/megabasterd/issues/215

Fix from same dev :)

**Comment by clonexplay-rgb** [comment]
https://mega.nz/file/i2xSkRaT
