### ISSUE TITLE
curl: option : blank argument where content is expected

### ISSUE THREAD

**Issue by pitsi** [tonikelope/megadown#33]
As mentioned in the title, when trying to download the following file, curl complains for a blank argument.
```
$ ./megadown 'https://mega.nz/file/MuQWCLoK#Ym581j7dRgVHnL22Pr-Qrqarx7JZGK9KHSR0QBXqDes'

Reading link metadata...
curl: option : blank argument where content is expected
curl: try 'curl --help' or 'curl --manual' for more information

Oooops, something went bad. EXIT CODE (2)
```
I think the syntax is correct. Sorry, but I have not used your tool for like 5+ years now.

**Comment by tonikelope** [comment]
It is necessary to use the old MEGA link format.

`https://mega.nz/#!MuQWCLoK!Ym581j7dRgVHnL22Pr-Qrqarx7JZGK9KHSR0QBXqDes`

**Comment by pitsi** [comment]
Thank you for pointing it out. As I said, I have not used megadown in years and I forgot about the old format.

**Comment by pitsi** [comment]
Small clarification because I am having the same issue again. In order to get the old mega format for the url, I substitute `/file` with `#!` and single `#` on the url with `!`? So this
`https://mega.nz/file/1nozQT5K#ymAL82fCJS8zn0yx1aSWstkUH9ZMp_t_FERbU2HXyEA`
becomes this
`https://mega.nz/#!1nozQT5K!ymAL82fCJS8zn0yx1aSWstkUH9ZMp_t_FERbU2HXyEA`
