### ISSUE TITLE
Wrong bash substitution ?

### ISSUE THREAD

**Issue by galtgendo** [tonikelope/megadown#7]
Well, it's not really testable, but it seems
```bash
link=${link//#!N?/#N!}
```
is not quite correct, as it breaks a link that starts with '#!N'.
Don't know much about bash, but was that '?' meant to be a literal '?', not a wildcard ?

**Comment by tonikelope** [comment]
This '?' is literal. There are no valid MEGA links starting with '#!N?'

This line is there for some time i see (i don't remember where) MEGA #N!xxxxxxx!zzzzzzzzzzzzzzz links in the form #!N?xxxxxx!zzzzzzzzzzzzzzz

Thanks for your time!

**Comment by galtgendo** [comment]
In such case, if I'm reading bash manpage correctly, perhaps that should go:
```bash
link=${link/\#!N\?/#N!}
```
or
```bash
link=${link/#\#!N\?/#N!}
```
?
The way I read it, you want to make only one substitution, at the start of the string with a literal '?'.
Though, would be better, if you could recall (and document) where did you see that form.

**Comment by tonikelope** [comment]
**You are RIGHT** -> '?' needs to be escaped 

Now any "normal" MEGA link with a FILE_ID starting with 'N' will be converted into a /#N! link, which is wrong. (I should read more slowly [https://www.gnu.org/software/bash/manual/html_node/Pattern-Matching.html](url) ) 

The goal of this pattern/replace line is to turn some link like this:

`https://mega.nz/#!N?[FILE_ID]![FILE_KEY]` 

into:

`https://mega.nz/#N![FILE_ID]![FILE_KEY]`

`link=${link//#!N\?/#N!}`  do the work (I have just tested it in Bash 4.4.5)

Thanks for your time!

**Comment by galtgendo** [comment]
Well, there's one other thing.

The way I read the manpage,
```bash
${var//pattern/string}
```

means replace *all* pattern instances, while you want only a single one.
Given what you've gathered about mega links syntax, there shouldn't be a second instance of the pattern, but why look for more than one in the first place ?

**Comment by tonikelope** [comment]
You are right again. In this case, it has no sense to look for a next pattern matching:

`link=${link/#!N\?/#N!}`

Thanks again for your time!
