### ISSUE TITLE
can't download , it gives an exit code of (3). 

### ISSUE THREAD

**Issue by a-eid** [tonikelope/megadown#8]
![](https://i.imgur.com/ikHzg9g.png)

can't figure how to use it.

**Comment by tonikelope** [comment]
Example link?

**Comment by Angristan** [comment]
Same here : 

```
root@server# ./megadown 'https://mega.nz/#F!scR3DBTQ!oZJiofaflaUcfhIarSHkXw'

Reading link metadata...

Oooops, something went bad. EXIT CODE (3)
```

**Comment by Guillaumebeuzeboc** [comment]
Hello,
I had the same issue because I was just copying the content of the `megadown` script. Git cloning the all repo make it works. I hope it can help.

**Comment by tonikelope** [comment]
Thanks @Guillaumebeuzeboc 

@Angristan folder links are not yet supported, sorry
